likelion/liongram/config/urls.py
from lotto import views
from django.contrib import admin
from django.urls import path,include
#from posts.views import url_view, url_parameter_view,function_view, class_view

urlpatterns = [
    path('',include('support.urls')),
    path('admin/', admin.site.urls),
    path('lotto/',include('lotto.urls')),
    path('support/',include('support.urls')),
    # path('url/',url_view),
    # path('url/<str:username>/',url_parameter_view),
    # path('url',function_view),
    # path('url',class_view.as_view()),
]

likelion/liongram/lotto/urls.py
from django.urls import path
from . import views
app_name = 'lotto'

urlpatterns = [
    path('', views.lotto ,name='lotto'), 
]

likelion/liongram/support/urls.py
from django.urls import path
from . import views

app_name = 'support'

urlpatterns = [
    path('', views.FaqListView.as_view() ,name='index'), 
    path('edit/<int:pk>', views.FaqEditView.as_view() ,name='edit'), 
    path('create/', views.FaqCreateView.as_view() ,name='create'), 
    path('detail/<int:pk>', views.FaqDetailView.as_view() ,name='detail'), 

]

likelion/liongram/lotto/models.py
from django.db import models

# Create your models here.

likelion/liongram/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Post(models.Model):
 
    content=models.TextField(verbose_name='내용')
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(verbose_name='이미지', null=True, blank = True)
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    view_count = models.IntegerField(verbose_name='조회수', default=0)
class Comment(models.Model):
     content = models.TextField(verbose_name='내용')
     created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
     post = models.ForeignKey(to='Post',on_delete=models.CASCADE)
     writer = models.ForeignKey(to=User,on_delete=models.CASCADE,null=True,blank=True)

likelion/liongram/support/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()


class Faq(models.Model):
    CATEGORY_ONE = '1'
    CATEGORY_TWO = '2'
    CATEGORY_THREE = '3'
    # 개발 원칙 : 의미가 불분명한 매직 넘버를 상수로 선언하라.
    CATEGORY_CHOICES =[
        (CATEGORY_ONE,'일반'),
        (CATEGORY_TWO,'계정'),
        (CATEGORY_THREE,'기타'),
    ]# 개발에서 사용하는 것은 1,2,3 사용자가 보는 것은 일반,계정,기타 를 본다.
    # 1,2,3 이나 알파벳을 통해 구분해야 이후 개발에서 외국에서 사용하거나, 개발시에 더 효율적으로 코딩이 가능하다.
    # 질문, 카테고리, 답변 생성자 생성일시 최종 수정자 최종수정일시
    title = models.CharField(verbose_name='제목',max_length=20)
    content = models.TextField(verbose_name='내용')
    category = models.CharField(verbose_name='카테고리',max_length=1, choices=CATEGORY_CHOICES)
    created_at = models.DateTimeField(verbose_name='생성일시',null=True,default=timezone.now)
    updated_at = models.DateTimeField(verbose_name='최종 수정일시',auto_now=True)
    # auto_now_add 처음 객체가 생성될 때만 변경
    # auto_now 객체가 저장될 때마다 변경
    created_by = models.ForeignKey(to=User, on_delete=models.CASCADE,related_name="faq_created_by")
    updated_by = models.ForeignKey(to=User, on_delete=models.CASCADE,related_name="faq_updated_by")
    # related_name은 어떤 유저인지 구분하기 위함이다. 하지만 코드의 일관성을 위해 항상 작성하는 습관을 들인다.



class Answer(models.Model):
    content = models.TextField(verbose_name='답변 글')
    answered_by = models.ForeignKey(to=User,on_delete=models.CASCADE)
    answered_at = models.DateTimeField(verbose_name="답변일시",null=True,default=timezone.now)
    faq = models.ForeignKey(to=Faq,on_delete=models.CASCADE)

likelion/liongram/lotto/views.py
from django.shortcuts import render,redirect

import random
# Create your views here.


def lotto(request):
    if request.method == 'GET':
        return render(request,'lotto_input.html')    
    else:
        arr = []
        number = int(request.POST.get('number'))
        for _ in range(number):
            temp =[]
            for _ in range(7):
                temp.append(random.randrange(1,50))
            arr.append(temp)
        context = {'count':number,'arr':arr}
        return render(request,'lotto.html',context)

likelion/liongram/posts/views.py
from django.shortcuts import render

# Create your views here.

# def function_view(request):
#     if request.method == 'GET':
#         print(f'request.GET:{request.GET}')
#     elif request.method=='POST':        
#         print(f'request.POST:{request.POST}')
#     return render(request,'view.html')

likelion/liongram/support/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, render
from django.views import generic
from .models import Faq, Answer

class FaqListView(generic.ListView):
    #model = models.Faq
    template_name = 'index.html'
    def get_queryset(self):
        return Faq.objects.order_by("-created_at")

class FaqEditView(generic.UpdateView):
    model = Faq
    template_name = 'edit_faq.html'

class FaqCreateView(generic.CreateView):
    model = Faq
    fields = ['title','category','content']
    template_name = 'create_faq.html'
    def create(request):
        faq = get_object_or_404(Faq)
        title = faq.title
        content = faq.content
        category = faq.category
        created_at = faq.created_at
        updated_at = faq.updated_at
        


class FaqDetailView(generic.DetailView):
    model = Faq
    template_name = 'detail_faq.html'

likelion/liongram/lotto/templates/lotto.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lotto</title>
</head>
<body>
    게임 수 : {{ number }}
    {% for temp in arr %}
    <br>

        {% for lotto_num in temp %}
            {{ lotto_num }}&nbsp;&nbsp;&nbsp;&nbsp;
        {% endfor %}
    {% endfor %}
    <br>
    <a href="/lotto/">돌아가기</a>
    <!-- /lotto/ -->

</body>
</html>

likelion/liongram/lotto/templates/lotto_input.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lotto input</title>
</head>
<body>
    <form action="{% url 'lotto:lotto' %}" method="POST">
        {% csrf_token %}
        <input type="number" name="number">
        <input type="submit" value="로또 번호 추출하기">
    </form>
</body>
</html>

likelion/liongram/posts/templates/cbv_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for object in objects %}
        <p>{{object}}</p>
    {% endfor %}
</body>
</html>

likelion/liongram/support/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} </title>
</head>
<body>
    <a href="/support/">질문 리스트</a>
    <form action="{% url 'support:create' %}" method="GET">
        <input type="submit" value="1대1 질문 생성">
    </form>
    {% block content %}
    {% endblock %}

</body>
</html>

likelion/liongram/support/templates/create_faq.html
{% extends 'base.html' %}
{% block title %} 질문 생성 {% endblock %}
{% block content %}
<form action="{% url 'support:create' %}">
    <input type="text" name="title"> <br>
    <textarea name="content" cols="30" rows="10"></textarea>
    <input type="submit" value="제출">
</form>
{% endblock %}

likelion/liongram/support/templates/detail_faq.html
{% extends 'base.html' %}
{% block title %} 커뮤니티 {% endblock %}
{% block content %}
        <p>{{ faq.title }}</p>
        <p>{{ faq.content }}</p>
        <form action="{% url 'support:edit_faq' faq.id %}" method="GET">
            <input type="submit" value="수정">
        </form>

{% endblock %}

likelion/liongram/support/templates/edit_faq.html
{% extends 'base.html' %}
{% block title %} 수정 {% endblock %}
{% block content %}
<form action="{% url 'support:edit' object_list.id %}" method="POST">
    {% csrf_token %}
    <input type="text" name="title" value="{{ object_list.title }}">
    <textarea name="content" cols="30" rows="10" value="{{ object_list.content }}"></textarea>
    <input type="submit" value="제출">
</form>
{% endblock %}

likelion/liongram/support/templates/index.html
{% extends 'base.html' %}
{% block title %} 커뮤니티 {% endblock %}
{% block content %}
    {% for faq in object_list %}
        <p>제목 : {{ faq.title }}</p>
        <p>내용 : {{ faq.content }}</p>
        <p>카테고리 : {{ faq.category }}</p>
        <p>생성일 : {{ faq.created_at }}</p>
        <p>생성자 : {{ faq.created_by }}</p>
        <p>수정일 : {{ faq.updated_at }}</p>
        <p>수정자 : {{ faq.updated_by }}</p>


        <form action="{% url 'support:edit' %}" method="GET">
            <input type="submit" value="수정">
        </form>
    {% endfor %}
{% endblock %}